Side filters
friendshipismagic/dreamworks pull request #12
Opened 2017-06-27 14:20 UTC by LSvt

Added selectors in the side menu to select datasets, gender, ... Unselected dreams are smaller.

2017-06-27 18:41 UTC, kaizensparc requested changes
?? Means 'I don't understand, could you explain?'
Dead file to remove (if it's in fact a dead file)

2017-06-27 18:41 UTC, didjcodt commented on frontend/js/bubble_chart.js
> +      //TODO
??

2017-06-27 18:41 UTC, didjcodt commented on frontend/js/bubble_chart.js
> +    //TODO: make this compact
??

2017-06-27 18:41 UTC, didjcodt commented on frontend/js/bubble_chart.js
> +    /*d3.selectAll(".inputRange")
Dead code here

2017-06-27 18:41 UTC, didjcodt commented on frontend/js/bubble_chart_old.js
> +//Charte graphique
Dead file ?

2017-06-27 22:37 UTC, LSvt commented
Removed dead code to address requested changes. Coded the order by year function.

2017-06-29 10:06 UTC, kaizensparc approved these changes
lgtm

2017-06-29 10:06 UTC, merged